#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#index:
#  path: /index
#  controller: App\Controller\MyController::index
#login:
#  path: /login
#  controller: App\Controller\MyController::login
#list:
#  path: /blog/list
#  controller: App\Controller\MyController::list
#about:
#  path: /about
#  controller: App\Controller\MyController::about